### ISSUE TITLE
Figure out why changed datafiles aren't refreshing in page object

### ISSUE THREAD

**Issue by zeke** [zeke/jus#17]

**Comment by elingerojo** [comment]
I think I figured out.
It is not just for `datafiles`, all other `types `are nor refreshing too (but `jus `features are not affected because they relay on object `files`)

### Short answer:
`event "squeezed"` only happen once at `server.start`
### Long answer:
The problem seems to be that `contextualize(files)` is called ONLY when `jus.tryToFinish()` is called. But this is also ONLY called once when `chokidar.on('ready", () => ...` event happens.

```

  function tryToFinish() {
    if (files.some(file => !file.squeezed)) return
    emitter.emit('squeezed', contextualize(files))
    clearInterval(tryToFinishInterval)
  }

```

The prove of this behavior is that `Et Voila!` message appear only once.
And protected by `if (server.started)` to run ONLY once.

> Et Voila!
> The server is running at http : //localhost:3000

```
    })
    .on('squeezed', (context) => {
      server.context = context
      if (server.started) return
      server.listen(server.port, function (err) {
        if (err) throw (err)
        server.started = true
        server.url = `http://localhost:${server.port}`
        log(`Et Voila!\nThe server is running at ${server.url}\n`)
        if (cb) return cb(null)
      })

```
## Solution
`contextualize()` must be called by event `'file-add'` and the options are:

1. Moving `contextualize()` to `jus.createFile()`
2. or coping `contextualize()` to `jus.createFile()` inside an `if (server.started)`
3. ... or other suggestions?

I want to work on it but will like to have your feedback.

**Comment by zeke** [comment]
@elingerojo if you have a vision for how to get this working, please run with it! Open up a PR and I will happily review it next week when I'm back online. 👍
