### ISSUE TITLE
any relation to gatsby?

### ISSUE THREAD

**Issue by jokeyrhyme** [zeke/jus#30]
This project seems to have similar goals to https://github.com/gatsbyjs/gatsby

Is it worth collaborating with those folks?

Nothing wrong with scratching your own itch, or trying out your own ideas, of course.

Just thought I'd mention it and start a conversation. :)

**Comment by zeke** [comment]
I hadn't seen Gatsby before. It looks like it does have some things in common, like markdown to HTML conversion, but from my perspective it's a very different project.

jus supports React and JSX through a babel transform, but React is totally optional.

jus also doesn't have any configuration. It is highly opinionated and aims to get as much right by default as possible. In general, this means:

- browserify all the javascript
- convert preprocessed styles to plain CSS
- make metadata about all pages available to all templates
- make metadata from JSON and YML files available to all templates
- support clean URLs

Because of its opinionated design and intentional lack of configuration, jus is probably not for everyone. But for those who just want to develop static sites using a browserify workflow, it might just do the trick.

**Comment by jokeyrhyme** [comment]
Okay cool, makes sense!
